### ISSUE TITLE
set elevation but nothing change

### ISSUE THREAD

**Issue by izzabellerina** [ChegzDev/gradient_elevated_button#2]
I have set the elevation and try to set background = white but the shadow nothing change 
how could I do

**Comment by ChegzDev** [comment]
Apologies for the inconvenience, @izzabellerina . I will resolve it soon.

**Comment by ChegzDev** [comment]
@izzabellerina fix this issue. now elevation and shadow will work normally.

**Comment by izzabellerina** [comment]
Thank you so much @ChegzDev
